{config, pkgs, ...}: let
  hostName = config.networking.hostName;
  suffix = config.networking.suffix;
  nextcloudAddress = "nextcloud.${hostName}.${suffix}";

  # UPGRADE THIS
  nextcloudVersion = 33;
  nextcloud = pkgs.${"nextcloud" + toString nextcloudVersion};
  nextcloudPackages = pkgs.${"nextcloud" + toString nextcloudVersion + "Packages"};
in {
  # technically, this is not necessary cause config.php is generated by an
  # activation script as root, but it would be if the secrets were accessed at
  # runtime. TODO keep an eye on this if it nextcloud breaks
  sops.secrets."nextcloud/admin_password".owner = "nextcloud";

  services.nextcloud = {
    enable = true;
    package = nextcloud;
    https = true;
    hostName = nextcloudAddress;
    home = "/srv/nextcloud";
    configureRedis = true;
    config = {
      dbtype = "pgsql";
      dbhost = "localhost";
      dbname = "nextcloud";
      dbpassFile = config.sops.secrets."postgresql/nextcloud".path;

      adminuser = "mrnobody";
      adminpassFile = config.sops.secrets."nextcloud/admin_password".path;
    };
    extraApps = with nextcloudPackages.apps; {
      inherit calendar
        contacts
        tasks
        whiteboard
        #end_to_end_encryption TODO reenable
        ;
    };
    settings = {
      defaultapp = "dashboard,files,calendar,contacts,end_to_end_encryption";
      appsallowlist = [
        "whiteboard"
        "tasks"
        "dashboard"
        "files"
        "calendar"
        "contacts"
        "end_to_end_encryption"
      ];
    };
  };

  security.acme.certs."${hostName}.${suffix}".extraDomainNames = [
    nextcloudAddress
  ];
  services.nginx.virtualHosts = {
    ${nextcloudAddress} = {
      useACMEHost = "${hostName}.${suffix}";
      acmeRoot = "/var/lib/acme/challenge-${hostName}-${suffix}";
      forceSSL = true;
    };
  };
}
