nix flake lock --update-input nixpkgs
nix flake lock --update-input unstable
nix flake lock --update-input home-manager
nix flake lock --update-input nixvim
nix flake lock --update-input sops-nix
nix flake lock --update-input impermanence
nix flake lock --update-input spicetify-nix
nix flake lock --update-input neovim-nightly-overlay
nix flake lock --update-input emacs-verlay
